-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 10:40:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sav_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sav_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sav_bd` DEFAULT CHARACTER SET utf8 ;
USE `sav_bd` ;

-- -----------------------------------------------------
-- Table `sav_bd`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`areas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`criterios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `id_area` INT(11) NOT NULL,
  `url_imagen` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CRITERIOS_AREAS1_idx` (`id_area` ASC),
  CONSTRAINT `fk_CRITERIOS_AREAS1`
    FOREIGN KEY (`id_area`)
    REFERENCES `sav_bd`.`areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`contenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`contenidos` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cod_grado` VARCHAR(10) NULL DEFAULT NULL,
  `id_criterio` INT(11) NOT NULL,
  `url_imagen` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CONTENIDOS_CRITERIOS1_idx` (`id_criterio` ASC),
  CONSTRAINT `fk_CONTENIDOS_CRITERIOS1`
    FOREIGN KEY (`id_criterio`)
    REFERENCES `sav_bd`.`criterios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`personas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido_paterno` VARCHAR(30) NOT NULL,
  `apellido_materno` VARCHAR(30) NOT NULL,
  `numero_celular` INT(9) NULL DEFAULT NULL,
  `correo` VARCHAR(60) NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  `cod_tipo_persona` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  INDEX `fk_usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sav_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`docentes` (
  `id` INT(11) NOT NULL,
  `id_persona` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PROFESORES_PERSONAS1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_PROFESORES_PERSONAS1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `sav_bd`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`subcontenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`subcontenidos` (
  `id` INT(11) NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `id_contenido` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `url_imagen` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DETALLE_CONTENIDOS_CONTENIDOS1_idx` (`id_contenido` ASC),
  CONSTRAINT `fk_DETALLE_CONTENIDOS_CONTENIDOS1`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `sav_bd`.`contenidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`recursos` (
  `id` INT(11) NOT NULL,
  `cod_tipo_recurso` VARCHAR(45) NULL DEFAULT NULL,
  `id_subcontenido` INT(11) NOT NULL,
  `url_recurso` VARCHAR(300) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `promedio_calificacion` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RECURSOS_DETALLE_CONTENIDOS1_idx` (`id_subcontenido` ASC),
  CONSTRAINT `fk_RECURSOS_DETALLE_CONTENIDOS1`
    FOREIGN KEY (`id_subcontenido`)
    REFERENCES `sav_bd`.`subcontenidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`preguntas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `puntaje` VARCHAR(45) NULL DEFAULT NULL,
  `cod_estado` VARCHAR(45) NULL DEFAULT NULL,
  `id_contenido` INT(11) NOT NULL,
  `respuesta_correcta` VARCHAR(20) NULL DEFAULT NULL,
  `id_recurso` INT(11) NOT NULL,
  `id_profesor` INT(11) NOT NULL,
  `url_imagen` VARCHAR(300) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PREGUNTAS_CONTENIDOS1_idx` (`id_contenido` ASC),
  INDEX `fk_PREGUNTAS_RECURSOS1_idx` (`id_recurso` ASC),
  INDEX `fk_PREGUNTAS_PROFESORES1_idx` (`id_profesor` ASC),
  CONSTRAINT `fk_PREGUNTAS_CONTENIDOS1`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `sav_bd`.`contenidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREGUNTAS_PROFESORES1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `sav_bd`.`docentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREGUNTAS_RECURSOS1`
    FOREIGN KEY (`id_recurso`)
    REFERENCES `sav_bd`.`recursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`alternativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`alternativas` (
  `id` INT(11) NOT NULL,
  `descripcion` VARCHAR(20) NULL DEFAULT NULL,
  `id_pregunta` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ALTERNATIVA_PREGUNTAS1_idx` (`id_pregunta` ASC),
  CONSTRAINT `fk_ALTERNATIVA_PREGUNTAS1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `sav_bd`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`estudiantes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `correo_apoderado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_personas_UNIQUE` (`id_persona` ASC),
  INDEX `fk_ALUMNOS_PERSONAS1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_ALUMNOS_PERSONAS1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `sav_bd`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`calificaciones` (
  `calificacion` INT(3) NULL DEFAULT NULL,
  `id_estudiante` INT(11) NOT NULL,
  `id_recurso` INT(11) NOT NULL,
  PRIMARY KEY (`id_estudiante`, `id_recurso`),
  UNIQUE INDEX `uk_evaluaciones` (`id_estudiante` ASC, `id_recurso` ASC),
  INDEX `fk_CALIFICACIONES_ALUMNOS1_idx` (`id_estudiante` ASC),
  INDEX `fk_CALIFICACIONES_RECURSOS1_idx` (`id_recurso` ASC),
  CONSTRAINT `fk_CALIFICACIONES_ALUMNOS1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sav_bd`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALIFICACIONES_RECURSOS1`
    FOREIGN KEY (`id_recurso`)
    REFERENCES `sav_bd`.`recursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`comentarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `id_recurso` INT(11) NOT NULL,
  `id_estudiante` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_COMENTARIOS_RECURSOS1_idx` (`id_recurso` ASC),
  INDEX `fk_COMENTARIOS_ALUMNOS1_idx` (`id_estudiante` ASC),
  CONSTRAINT `fk_COMENTARIOS_ALUMNOS1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sav_bd`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIOS_RECURSOS1`
    FOREIGN KEY (`id_recurso`)
    REFERENCES `sav_bd`.`recursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`grupos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cod_grado` VARCHAR(45) NOT NULL,
  `cod_estado` VARCHAR(45) NOT NULL,
  `id_docente` INT(11) NOT NULL,
  `anio` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GRUPOS_PROFESORES1_idx` (`id_docente` ASC),
  CONSTRAINT `fk_GRUPOS_PROFESORES1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `sav_bd`.`docentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`evaluaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `cod_tipo_evaluacion` VARCHAR(45) NOT NULL,
  `id_docente` INT(11) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `id_contenido` INT(11) NULL DEFAULT NULL,
  `id_grupo` INT(11) NOT NULL,
  `cod_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EVALUACIONES_PROFESORES1_idx` (`id_docente` ASC),
  INDEX `fk_contenido_idx` (`id_contenido` ASC),
  INDEX `FK_id_grupo_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_EVALUACIONES_PROFESORES1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `sav_bd`.`docentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `sav_bd`.`contenidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `sav_bd`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`estudiante_evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`estudiante_evaluaciones` (
  `id_estudiante` INT(11) NOT NULL,
  `id_evaluacion` INT(11) NOT NULL,
  `id_area` INT(11) NOT NULL,
  `nota` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_entrega` DATETIME NULL DEFAULT NULL,
  `cod_estado_evaluacion` VARCHAR(10) NULL DEFAULT NULL,
  `id_grupo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estudiante`, `id_evaluacion`, `id_area`),
  INDEX `fk_ALUMNOS_has_EVALUACIONES_EVALUACIONES1_idx` (`id_evaluacion` ASC),
  INDEX `fk_ALUMNOS_has_EVALUACIONES_ALUMNOS1_idx` (`id_estudiante` ASC),
  INDEX `fk_ALUMNOS_has_EVALUACIONES_AREAS1_idx` (`id_area` ASC),
  CONSTRAINT `fk_ALUMNOS_has_EVALUACIONES_ALUMNOS1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sav_bd`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNOS_has_EVALUACIONES_AREAS1`
    FOREIGN KEY (`id_area`)
    REFERENCES `sav_bd`.`areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNOS_has_EVALUACIONES_EVALUACIONES1`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `sav_bd`.`evaluaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`evaluacion_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`evaluacion_detalles` (
  `id_evaluacion` INT(11) NOT NULL,
  `id_pregunta` INT(11) NOT NULL,
  PRIMARY KEY (`id_evaluacion`, `id_pregunta`),
  INDEX `fk_EVALUACIONES_has_PREGUNTAS_PREGUNTAS1_idx` (`id_pregunta` ASC),
  INDEX `fk_EVALUACIONES_has_PREGUNTAS_EVALUACIONES1_idx` (`id_evaluacion` ASC),
  CONSTRAINT `fk_EVALUACIONES_has_PREGUNTAS_EVALUACIONES1`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `sav_bd`.`evaluaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVALUACIONES_has_PREGUNTAS_PREGUNTAS1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `sav_bd`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`historiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`historiales` (
  `id_estudiante` INT(11) NOT NULL,
  `json_completo` LONGTEXT NULL DEFAULT NULL,
  `json_estadistica` LONGTEXT NULL DEFAULT NULL,
  `id_evaluacion` INT(11) NOT NULL,
  `fecha_finalizacion` DATETIME NULL DEFAULT NULL,
  `tipo_evaluacion` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estudiante`, `id_evaluacion`),
  INDEX `fk_ESTUDIANTE_has_EVALUACION_DETALLES_ESTUDIANTE1_idx` (`id_estudiante` ASC),
  INDEX `fk_HISTORIAL_EVALUACIONES1_idx` (`id_evaluacion` ASC),
  CONSTRAINT `fk_ESTUDIANTE_has_EVALUACION_DETALLES_ESTUDIANTE1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sav_bd`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIAL_EVALUACIONES1`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `sav_bd`.`evaluaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`tabla_maestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`tabla_maestra` (
  `id_tabla_maestra` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tabla_maestra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`maestra_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`maestra_detalles` (
  `codigo` VARCHAR(10) NOT NULL,
  `id_tabla_maestra` INT(11) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `abreviatura` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`, `id_tabla_maestra`),
  INDEX `fk_MAESTRA_DETALLES_TABLA_MAESTRA1` (`id_tabla_maestra` ASC),
  CONSTRAINT `fk_MAESTRA_DETALLES_TABLA_MAESTRA1`
    FOREIGN KEY (`id_tabla_maestra`)
    REFERENCES `sav_bd`.`tabla_maestra` (`id_tabla_maestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`matriculas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  `fecha_matricula` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `id_estudiante`, `id_grupo`),
  UNIQUE INDEX `id_grupo_UNIQUE` (`id_grupo` ASC, `id_estudiante` ASC),
  INDEX `fk_MATRICULAS_ALUMNOS1_idx` (`id_estudiante` ASC),
  INDEX `fk_MATRICULAS_GRUPOS1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_MATRICULAS_ALUMNOS1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sav_bd`.`estudiantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULAS_GRUPOS1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `sav_bd`.`grupos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`roles` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`test` (
  `id_test` INT(11) NOT NULL,
  `campo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_test`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sav_bd`.`usuarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sav_bd`.`usuarios_roles` (
  `usuarios_id` INT(11) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  INDEX `fk_roles_idx` (`roles_id` ASC),
  INDEX `fk_usuarios_03` (`usuarios_id` ASC),
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `sav_bd`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_03`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sav_bd`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
